export const constants = {
    accommodationOwnership:"2",
    accommodationType:"2",
    age:"0",
    annualWage:"2",
    area:"1",
    canServeHimself:"2",
    city:"51",
    familyIncome:"2",
    fatherName:"yousef",
    firstName:"heba t2shera",
    gender:"F",
    gregorianVisaExpirationDate:"Sun May 01 2033 00:00:00 GMT+0300 (GMT+03:00)",
    hijriVisaExpirationDate:"Fri Feb 02 1455 00:00:00 GMT+0223 (GMT+03:00)",
    identityType:"visa_number",
    jobless:"1",
    lastName:"foudeh",
    maritalStatus:"2",
    nationality:"الاردن",
    numberOfFamilyMembers:"2",
    patientIncome:"2",
    phases:"",
    publishOnCharityPage:"false",
    searchType:"1",
    shefaaExclusiveFlag:"false",
    socialStatus:"2",
    splitIntoPhases:"false",
    waitingTechnicalAuditorApprovalStatus:"Technical_Audit",
    waitingMedicalAuditorApprovalStatus:"Medical_Audit",
    waitingMarketingAuditorApprovalStatus: "Marketing_Audit",
    termsAndConditionsFlag:"true",
    worthyOfZakah:"1",
    createCaseUrl: "/charity/case",
    caseUrl: "/charity/case/",
    caseDetailsUrl: "/charity/case/details/",
    caseObjType: "obj_type=case",
    gregorianBirthdateAuditors: "01-05-2023",
    hijriBirthdateAuditors: "11-10-1444",
    genderAuditors: "أنثى",
    specialty: "5",
    actionType: "1",
    actionDescription: "4",
    evaluation: "2",
    publishDuration: 0,
    waitingFinalApprovalStatus: 'Final_Audit',
    readyToBePublishedStatus: 'Ready_to_be_Published',
    publishedStatus: 'Published',
    invoicingUrl: '/invoicing',
    paymentRequestUrl: '/payment_request_create_apiview',
    hospital: "1"
};