export const constants = {
    visaNumber: '3321458674',
    gregorianBirthdate: '2023-05-01',
    hijriBirthdate: '1444-10-11',
    gregorianVisaExpirationDate: '2033-05-01',
    hijriVisaExpirationDate: '1455-02-02',
    address: 'شارع 1',
    phone: '0512321235',
    financialCost: '4500',
    job: 'معلم',
    caseStory: 'يعاني المريض من آلام شديدة بسبب المرض',
    idPhotoFilePath: 'playwright/constants/attachments/idPhoto.png',
    medicalReportFilePath: 'playwright/constants/attachments/medical-report.pdf',
    financialCostFilePath: 'playwright/constants/attachments/financial-cost.pdf',
    waitingTechnicalAuditor: 'بانتظار التدقيق الفني',
    married:  'متزوج',
    widower: 'أرمل',
    needHelp: 'يحتاج إلى مساعدة',
    No: 'لا',
    room: 'غرفة',
    rent: 'إيجار',
    lessThan5000: 'أقل من 5000 ر.س',
    five: '5',
    lessThan1500: 'أقل من 1,500 ر.س',
    lessThan2500: 'أقل من 2,500 ر.س',
    call: 'اتصال',
    charityName: 'المنال',
    visa: 'تأشيرة',
    riyad: 'الرياض',
    shaqra: 'شقراء',
    gregorianBirthdateView: '01-05-2023',
    hijriBirthdateView: '11-10-1444',
    gregorianVisaExpirationDateView: '01-05-2033',
    phoneView: '05-12321235',
    idPhotoFileName: 'idPhoto',
    medicalReportFileName: 'medical-report',
    financialCostFileName: 'financial-cost',
    waitingMedicalAuditor: "بانتظار التدقيق الطبي",
    waitingMarketingAuditor: 'بانتظار الإعداد التسويقي',
    waitingFinalApproval: 'بانتظار القبول النهائي',
    readyToPublish: 'جاهز للنشر',
    published: 'منشور',
    invoiceNumber: '123',
    invoiceFilePath: 'playwright/constants/attachments/invoice.pdf',
    invoiceNotes: "إضافة فاتورة إلى الحالة",
    hospital: "مستشفى الامير فهد",
    invoiceFileName: 'invoice.pdf',
    waitingFirstFinancialAuditor: 'بانتظار التدقيق المالي 1',
    waitingInvoice: 'بانتظار الفاتورة',
    collectedAmount: '4,950'
};
