export const constants = {
    approveAndSendToMedicalAuditorText: 'قبول وارسال للمدقق الطبي',
    technicalAuditorInternalNotesText: 'أنا كمدير فني أقبل هذا الطلب وأرسله للمدقق الطبي',
    approveAndSendToMarketingAuditorText: 'قبول وارسال للإعداد التسويقي',
    technicalAuditor: 'مدقق فني',
    specialtyText: 'الجهاز الهضمي',
    actionTypeText: 'عملية جراحية',
    actionDescriptionText: 'جلسات غسيل كلى',
    caseEvaluationText: 'غير عاجلة',
    medicalAuditor: 'مدقق طبي',
    medicalAuditorInternalNotesText: 'أنا كمدير طبي أقبل هذا الطلب وأرسله للمدقق التسويقي',
    approveAndSendToFinalRevisionText: 'قبول وإرسال للمراجعة النهائية',
    storyTitleText: 'مشكلة في الجهاز الهضمي',
    shownStoryText: 'يعاني المريض من آلام حادة في الجهاز الهضمي ويحتاج إلى عملية جراحية',
    storyPhotoFilePath: 'playwright/constants/attachments/story.png',
    marketingAuditor: 'مدقق تسويقي',
    marketingAuditorInternalNotesText: 'أنا كمدقق تسويقي أقبل هذا الطلب وأرسله للمراجعة النهائية',
    storyPhotoFileName: 'story',
    systemAdmin: 'مدير نظام',
    approveAndSendToBeReadyToPublishText: 'إعتماد وارسال للجاهز للنشر',
    systemAdminReadyToPublishInternalNotesText: 'أنا كمدير نظام أقبل هذا الطلب و أرسله ليكون جاهزا للنشر',
    publishCaseText: 'نشر الحالة',
    systemAdminPublishInternalNotesText: 'أنا كمدير نظام أرسل هذا الطلب للنشر',
    firstFinancialAuditor: 'مدقق مالي أول'
}